language: node_js
sudo: required
dist: trusty
addons:
  chrome: stable
before_script:
  - 'sudo chown root /opt/google/chrome/chrome-sandbox'
  - 'sudo chmod 4755 /opt/google/chrome/chrome-sandbox'
cache:
  yarn: true

notifications:
  email: false

node_js: 10

install:
  - yarn install --no-lockfile --non-interactive

stages:
  - 'Tests'
  - name: 'Deploy'
    if: branch = master AND type = push

jobs:
  fail_fast: true
  include:
    - stage: 'Tests'
      name: 'Fixed Dependencies'
      script:
        - commitlint-travis
        - node ./scripts/problems.js
        - yarn test
      install: yarn install --non-interactive
    - name: 'Floating Dependencies'
    - stage: 'Deploy'
      name: 'Publish to npm'
      install:
        - yarn install --non-interactive
      script: yarn semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
